"""empty message

Revision ID: 3acf81d07f5c
Revises: c9df80e38976
Create Date: 2025-01-18 16:18:08.863683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3acf81d07f5c'
down_revision: Union[str, None] = 'c9df80e38976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_client', 'firstName',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dim_client', 'lastName',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dim_client', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dim_client', 'auth0Id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dim_client', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dim_client', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dim_client', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dim_client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_auth0Id', 'dim_client', ['auth0Id'], unique=False)
    op.create_index('idx_email', 'dim_client', ['email'], unique=False)
    op.create_index(op.f('ix_dim_client_auth0Id'), 'dim_client', ['auth0Id'], unique=True)
    op.create_index(op.f('ix_dim_client_email'), 'dim_client', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dim_client_email'), table_name='dim_client')
    op.drop_index(op.f('ix_dim_client_auth0Id'), table_name='dim_client')
    op.drop_index('idx_email', table_name='dim_client')
    op.drop_index('idx_auth0Id', table_name='dim_client')
    op.alter_column('dim_client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('dim_client', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('dim_client', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dim_client', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dim_client', 'auth0Id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dim_client', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dim_client', 'lastName',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dim_client', 'firstName',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
